const data = {
  products: [
    {
      id: 1,
      category: "MEN",
      name: "Essentials Hoddie White",
      price: 69999,
      quantity: 1,
      ratings: 3,
      image: require("../Images/pic1.png"),
    },
    {
      id: 2,
      category: "MEN",
      name: "Levis Mens Dark Jeans",
      price: 2450,
      quantity: 1,
      ratings: 4,
      image: require("../Images/pic2.png"),
    },
    {
      id: 3,
      category: "MEN",
      name: "Dior Chelsea Boots",
      price: 8000,
      quantity: 1,
      ratings: 4,
      image: require("../Images/pic3.png"),
    },
    {
      id: 4,
      category: "MEN",
      name: "Dr Martin Boots",
      price: 15200,
      quantity: 1,
      ratings: 2,
      image: require("../Images/pic4.png"),
    },
    {
      id: 5,
      category: "MEN",
      name: "Converse Black Chuks",
      price: 6900,
      quantity: 1,
      ratings: 4,
      image: require("../Images/pic5.png"),
    },
    {
      id: 6,
      category: "MEN",
      name: "Levis Jeans Jacket",
      price: 3000,
      quantity: 1,
      ratings: 4,
      image: require("../Images/pic6.png"),
    },

    {
      id: 7,
      category: "MEN",
      name: "Zara Suede Jacket",
      price: 3500,
      quantity: 1,
      ratings: 4,
      image: require("../Images/pic7.png"),
    },
    {
      id: 8,
      category: "MEN",
      name: "Mens Arrow Head Necklace",
      price: 300,
      quantity: 1,
      ratings: 4,
      image: require("../Images/pic8.png"),
    },
  ],
};

export default data;
